version: '2.0'
services:
    postgresql:
        build:
            context: ./postgres
            args:
                - POSTGRES_USER=modbot
                - POSTGRES_PASSWORD=postgres
                - POSTGRES_DB=modtools
        volumes:
          - './data:/var/lib/postgresql/'
        expose:
            - "5432"
    python:
        build:
            context: "modtools"
        volumes: 
            - './modtools:/modtools' 
